### ISSUE TITLE
Make bounding box work in Chrome

### ISSUE THREAD

**Issue by hbredin** [ghostsphinx/web-evidence#2]
Not mandatory (if we know it works in Firefox) but would be a nice improvement.

**Comment by ghostsphinx** [comment]
Done.

**Comment by hbredin** [comment]
Pour info : tu peux fermer automatiquement un "issue" si tu mets quelque chose comme "closes #2" dans ton commit message -- cf https://help.github.com/articles/closing-issues-via-commit-messages/
