### ISSUE TITLE
Warn the annotator about "spoken" names

### ISSUE THREAD

**Issue by hbredin** [ghostsphinx/web-evidence#5]
By default, the annotator will not even listen to the audio to take a decision.
This is ok if he is supposed to look for a "written" name. 

However, this is **not** ok in case of "spoken" names.
We should probably put a warning somewhere saying "careful: the person name is likely to only be found in the audio". 

I think (but did not check) that the current version displays an alert when this is the case... but it'd be better to find another way to warn the annotator.

**Comment by ghostsphinx** [comment]
New version of the warning, if you agree with it, I can close.
EDIT: I forgot to erase it after changing evidence, but it will be done quickly.

**Comment by hbredin** [comment]
Can you upload a screenshot of what it does here?
I have no (easy and quick) way of testing it...

May I suggest you have a look at http://getbootstrap.com/components/#alerts ?
I think it may "feel" nicer to the user :)

**Comment by ghostsphinx** [comment]
![pronounced](https://cloud.githubusercontent.com/assets/11330085/16515576/06ff3138-3f73-11e6-9c49-f4da8a80e3c1.png)
Just over the video (but the location is not important I presume).

**Comment by hbredin** [comment]
OK. Nice! 

I would change the message to: 

WARNING: the person name might be pronounced!

**Comment by ghostsphinx** [comment]
Thank you, the message is changed, and I can do the same for the alert "Draw a bounding box".
