### ISSUE TITLE
Validation on Chrome

### ISSUE THREAD

**Issue by ghostsphinx** [ghostsphinx/web-evidence#6]
Buttons are not working properly on Chrome browser.

**Comment by ghostsphinx** [comment]
Buttons were not working at all, the blocking code was removed.

**Comment by hbredin** [comment]
Looks like it still does not work in my Chrome...
Mac OS X v10.11.3
Chrome v51.0.2704.103 (64-bit)

**Comment by hbredin** [comment]
My bad -- this is fixed in my Chrome as well...
